name: budge_food
description: school-fd refurbished

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_tab_indicator: ^0.1.5
  gradient_widgets: ^0.5.1
  provider: ^5.0.0
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  http: ^0.13.3
  smooth_star_rating: ^1.1.1
  flutter_gradient_colors: ^1.0.0
  outline_gradient_button: ^2.0.0+1
  lottie: ^1.0.1
  shared_preferences: ^0.5.3+1
#  firebase_auth: ^1.2.0
#



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/snacks/
    - images/food/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
      - asset: fonts/Pacifico.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
